In [1]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [2]:
import os
import zipfile
import pandas as pd

# Function to extract and read data from a zip file
def read_zip_data(zip_file_path):
    num_data = []
    sub_data = []

    with zipfile.ZipFile(zip_file_path, 'r') as zip_file:
        with zip_file.open('num.txt') as num_file:
            num_data = pd.read_csv(num_file, sep='\t')
        with zip_file.open('sub.txt') as sub_file:
            sub_data = pd.read_csv(sub_file, sep='\t')

    return num_data, sub_data

# Input path containing multiple zip files
input_path = "gdrive/My Drive/Colab Notebooks/SEC_Data"

num_dataframes = []
sub_dataframes = []

# Loop through zip files in the input directory
for root, dirs, files in os.walk(input_path):
    for file in files:
        if file.endswith(".zip"):
            zip_file_path = os.path.join(root, file)
            num_df, sub_df = read_zip_data(zip_file_path)
            num_dataframes.append(num_df)
            sub_dataframes.append(sub_df)

# Concatenate dataframes from all zip files
if num_dataframes:
    num_dataframe = pd.concat(num_dataframes, ignore_index=True)
    sub_dataframe = pd.concat(sub_dataframes, ignore_index=True)

    # You can now work with the num_dataframe and sub_dataframe as needed
    print("Dataframes for num.txt and sub.txt are created.")
    print("num_dataframe:")
    print(num_dataframe.head())
    print("sub_dataframe:")
    print(sub_dataframe.head())
else:
    print("No zip files found in the specified directory.")

Dataframes for num.txt and sub.txt are created.
num_dataframe:
                   adsh                                                tag  \
0  0001140361-22-040133        AcceleratedShareRepurchaseProgramAdjustment
1  0001140361-22-040134        AcceleratedShareRepurchaseProgramAdjustment
2  0001140361-22-040134        AcceleratedShareRepurchaseProgramAdjustment
3  0001628280-22-028255        AcceleratedShareRepurchaseProgramAdjustment
4  0000860413-22-000202  AcceleratedShareRepurchasesAdjustmentToRecorde...

        version coreg     ddate  qtrs  uom        value footnote
0  us-gaap/2021   NaN  20220331     1  USD -150000000.0      NaN
1  us-gaap/2021   NaN  20220331     1  USD -150000000.0      NaN
2  us-gaap/2021   NaN  20220630     1  USD          0.0      NaN
3  us-gaap/2021   NaN  20220930     1  USD   20010000.0      NaN
4  us-gaap/2021   NaN  20220930     3  USD  197400000.0      NaN
sub_dataframe:
                   adsh    cik                    name     sic countryba  \
0  0000014707-22-000072  14707             CALERES INC  3140.0        US
1  0000014846-22-000059  14846    BRT APARTMENTS CORP.  6798.0        US
2  0000018349-22-000191  18349  SYNOVUS FINANCIAL CORP  6021.0        US
3  0000035527-22-000248  35527     FIFTH THIRD BANCORP  6022.0        US
4  0000041719-22-000063  41719         GLATFELTER CORP  2621.0        US

  stprba      cityba       zipba                  bas1                bas2  \
0     MO    ST LOUIS       63105     8300 MARYLAND AVE          P O BOX 29
1     NY  GREAT NECK  11021-3190     60 CUTTER MILL RD           SUITE 303
2     GA    COLUMBUS       31901       1111 BAY AVENUE             STE 500
3     OH  CINCINNATI       45263    38 FOUNTAIN SQ PLZ  FIFTH THIRD CENTER
4     NC   CHARLOTTE       28209  4350 CONGRESS STREET           SUITE 600

   ...      period      fy   fp     filed               accepted prevrpt  \
0  ...  20221031.0  2022.0   Q3  20221206  2022-12-06 14:50:00.0       0
1  ...  20221130.0     NaN  NaN  20221206  2022-12-06 16:16:00.0       0
2  ...  20221130.0     NaN  NaN  20221206  2022-12-06 16:16:00.0       0
3  ...  20221130.0     NaN  NaN  20221206  2022-12-06 17:01:00.0       0
4  ...  20221130.0     NaN  NaN  20221206  2022-12-06 16:47:00.0       0

  detail                  instance nciks  aciks
0      1  cal-20221029x10q_htm.xml     1    NaN
1      0      brt-20221206_htm.xml     1    NaN
2      0      syn-20221206_htm.xml     1    NaN
3      0     fitb-20221206_htm.xml     1    NaN
4      0      glt-20221202_htm.xml     1    NaN

[5 rows x 36 columns]

In [3]:
num_dataframe.shape

(2701629, 9)

In [4]:
num_dataframe.to_csv("gdrive/My Drive/Colab Notebooks/SEC_Data/num.csv")
sub_dataframe.to_csv("gdrive/My Drive/Colab Notebooks/SEC_Data/sub.csv")